app: "facebook"

provider:
  name: aws
  region: us-east-1

auth:
  role_arn: arn:aws:iam::111111111111:role/BackupExecutionRole

protect:
  schedule: daily@3am
  retention: 7d
  resources:
    - type: rds
      identifier: prod-db-cluster
      tags: "tag: Owner=devops"

